apiVersion: v1                                       
kind: ConfigMap                                      
metadata:                                            
  name: "{{ include "pgbouncer.fullname" . }}"
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}                   
data:
  pgbouncer.ini: |
    [databases]
    {{- range $key, $value := .Values.pgbouncer.databases }}
    {{ $key }} = auth_user={{ $value.user }} host={{ $value.host }} port={{ default 5432 $value.port }}
    {{- if $value.client_encoding }} client_encoding={{ $value.client_encoding }}{{- end -}}
    {{- if $value.datestyle }} datestyle={{ $value.datestyle }}{{- end -}}
    {{- if $value.timezone }} timezone={{ $value.timezone }}{{- end -}}
    {{- if $value.pool_size }} pool_size={{ $value.pool_size }}{{- end -}}
    {{- if $value.reserve_pool }} reserve_pool={{ $value.reserve_pool }}{{- end -}}
    {{- if $value.max_db_connections }} max_db_connections={{ $value.max_db_connections }}{{- end -}}
    {{- if $value.pool_mode }} pool_mode={{ $value.pool_mode }}{{- end -}}
    {{- if $value.connect_query }} connect_query={{ $value.connect_query }}{{- end -}}
    {{- if $value.application_name }} application_name={{ $value.application_name }}{{- end -}}
    {{ end }}
    [users]
    [pgbouncer]
    logfile = /var/log/pgbouncer/pgbouncer.log
    pidfile = /var/run/pgbouncer/pgbouncer.pid
    listen_addr = 0.0.0.0
    listen_port = {{ .Values.pgbouncer.port }}
    client_tls_sslmode = {{ .Values.pgbouncer.ssl.client.tls_sslmode }}
    client_tls_ca_file = {{ .Values.pgbouncer.ssl.client.tls_ca_file }}
    client_tls_key_file = {{ .Values.pgbouncer.ssl.client.tls_key_file }}
    client_tls_cert_file = {{ .Values.pgbouncer.ssl.client.tls_cert_file }}
    client_tls_ciphers = {{ .Values.pgbouncer.ssl.client.tls_ciphers }}
    client_tls_protocols = {{ .Values.pgbouncer.ssl.client.tls_protocols }}
    client_tls_dheparams = {{ .Values.pgbouncer.ssl.client.tls_dheparams }}
    client_tls_ecdhcurve = {{ .Values.pgbouncer.ssl.client.tls_ecdhcurve }}
    server_tls_sslmode = {{ .Values.pgbouncer.ssl.server.tls_sslmode }}
    server_tls_ca_file = {{ .Values.pgbouncer.ssl.server.tls_ca_file }}
    server_tls_key_file = {{ .Values.pgbouncer.ssl.server.tls_key_file }}
    server_tls_cert_file = {{ .Values.pgbouncer.ssl.server.tls_cert_file }}
    server_tls_protocols = {{ .Values.pgbouncer.ssl.server.tls_protocols }}
    server_tls_ciphers = {{ .Values.pgbouncer.ssl.server.tls_ciphers }}
    auth_type = {{ .Values.pgbouncer.auth.auth_type }}
    auth_file = /etc/pgbouncer/userlist.txt
    {{- if eq .Values.pgbouncer.auth.type "hba" -}}
    auth_hba_file = /etc/pgbouncer.hba.conf
    {{- end }}
    auth_query = {{ .Values.pgbouncer.auth.auth_query }}
    pool_mode = {{ .Values.pgbouncer.pooler.pool_mode }}
    server_reset_query = {{ .Values.pgbouncer.pooler.server_reset_query }}
    server_reset_query_always = {{ .Values.pgbouncer.pooler.server_reset_query_always }}
    ignore_startup_parameters = {{ .Values.pgbouncer.pooler.ignore_startup_parameters }}
    server_check_query = {{ .Values.pgbouncer.pooler.server_check_query }}
    server_check_delay = {{ .Values.pgbouncer.pooler.server_check_delay }}
    server_fast_close = {{ .Values.pgbouncer.pooler.server_fast_close }}
    application_name_add_host = {{ .Values.pgbouncer.pooler.application_name_add_host }}
    stats_period = {{ .Values.pgbouncer.pooler.stats_period }}
    max_client_conn = {{ .Values.pgbouncer.connection_limits.max_client_conn }}
    default_pool_size = {{ .Values.pgbouncer.connection_limits.default_pool_size }}
    min_pool_size = {{ .Values.pgbouncer.connection_limits.min_pool_size }}
    reserve_pool_size = {{ .Values.pgbouncer.connection_limits.reserve_pool_size }}
    reserve_pool_timeout = {{ .Values.pgbouncer.connection_limits.reserve_pool_timeout }}
    max_db_connections = {{ .Values.pgbouncer.connection_limits.max_db_connections }}
    max_user_connections = {{ .Values.pgbouncer.connection_limits.max_user_connections }}
    server_round_robin = {{ .Values.pgbouncer.connection_limits.server_round_robin }}
    syslog = 0
    syslog_facility = daemon
    syslog_ident = pgbouncer
    log_connections = {{ .Values.pgbouncer.logging.log_connections }}
    log_disconnections = {{ .Values.pgbouncer.logging.log_disconnections }}
    log_pooler_errors = {{ .Values.pgbouncer.logging.log_pooler_errors }}
    log_stats = {{ .Values.pgbouncer.logging.log_stats }}
    verbose = {{ .Values.pgbouncer.logging.verbose }}
    server_lifetime = {{ .Values.pgbouncer.timeouts.server_lifetime }}
    server_idle_timeout = {{ .Values.pgbouncer.timeouts.server_idle_timeout }}
    server_connect_timeout = {{ .Values.pgbouncer.timeouts.server_connect_timeout }}
    server_login_retry = {{ .Values.pgbouncer.timeouts.server_login_retry }}
    query_timeout = {{ .Values.pgbouncer.timeouts.query_timeout }}
    query_wait_timeout = {{ .Values.pgbouncer.timeouts.query_wait_timeout }}
    client_idle_timeout = {{ .Values.pgbouncer.timeouts.client_idle_timeout }}
    client_login_timeout = {{ .Values.pgbouncer.timeouts.client_login_timeout }}
    autodb_idle_timeout = {{ .Values.pgbouncer.timeouts.autodb_idle_timeout }}
    idle_transaction_timeout = {{ .Values.pgbouncer.timeouts.idle_transaction_timeout }}
    suspend_timeout = {{ .Values.pgbouncer.timeouts.suspend_timeout }}
    pkt_buf = {{ .Values.pgbouncer.tuning.pkt_buf }}
    listen_backlog = {{ .Values.pgbouncer.tuning.listen_backlog }}
    sbuf_loopcnt = {{ .Values.pgbouncer.tuning.sbuf_loopcnt }}
    max_packet_size = {{ .Values.pgbouncer.tuning.max_packet_size }}
    so_reuseport = {{ .Values.pgbouncer.tuning.so_reuseport }}
    tcp_defer_accept = {{ .Values.pgbouncer.tuning.tcp_defer_accept }}
    tcp_socket_buffer = {{ .Values.pgbouncer.tuning.tcp_socket_buffer }}
    tcp_keepalive = {{ .Values.pgbouncer.tuning.tcp_keepalive }}
    tcp_keepcnt = {{ .Values.pgbouncer.tuning.tcp_keepcnt }}
    tcp_keepidle = {{ .Values.pgbouncer.tuning.tcp_keepidle }}
    tcp_keepintvl = {{ .Values.pgbouncer.tuning.tcp_keepintvl }}
    tcp_user_timeout = {{ .Values.pgbouncer.tuning.tcp_user_timeout }}
    dns_max_ttl = {{ .Values.pgbouncer.tuning.dns_max_ttl }}
    dns_zone_check_period = {{ .Values.pgbouncer.tuning.dns_zone_check_period }}
    dns_nxdomain_ttl = {{ .Values.pgbouncer.tuning.dns_nxdomain_ttl }}
    resolv_conf = {{ .Values.pgbouncer.tuning.resolv_conf }}

    ;;;
    ;;; Random stuff
    ;;;

    ;; Hackish security feature.  Helps against SQL injection when PQexec
    ;; is disabled, multi-statement cannot be made.
    ;disable_pqexec = 0

    ;; Config file to use for next RELOAD/SIGHUP
    ;; By default contains config file from command line.
    ;conffile

    ;; Windows service name to register as.  job_name is alias for
    ;; service_name, used by some Skytools scripts.
    ;service_name = pgbouncer
    ;job_name = pgbouncer

    ;; Read additional config from other file
    ;%include /etc/pgbouncer/pgbouncer-other.ini
  pg_hba.conf: |
    {{- range .Values.pgbouncer.hba }}
    {{ .recordType }} {{ .database }} {{ .username }} {{ .address }} {{ .authMethod }}
    {{- end -}}