apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "pgbouncer.fullname" . }}"
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
  userlist: |
    {{- range $key, $value := .Values.pgbouncer.users }}
    "{{ $key }}" "{{ $value }}"
    {{- end -}}